### PR TITLE
Speed up add-edges*

### PR DESCRIPTION
**Pull request by mattrepl**
I was constructing a graph with ~30 million edges and noticed that the current implementations of add-edges* don't take advantage of transient data structures. I modified the BasicEditableGraph implementation and had an anecdotal speed-up of 1 hour to 3 min for adding the edges.

If this change is acceptable, similar modifications should be made to the other add-edges* implementations.

### CODE REVIEW

**Comment by mattrepl** [comment]
Hey @aysylu , was this change OK? I'm running into an issue with the performance of add-edges* for BasicEditableWeightedGraph and was going to update its implementation in a similar fashion.

**Comment by aysylu** [comment]
Hey @mattrepl, could you please run this before the changes and after with criterium on 1) your graph and 2) a graph with 10 nodes + edges and include the output of criterium in the PR? Also, please add a test for `add-edges` that adds multiple edges, since I believe that behavior isn't properly covered by the tests. Thanks!

**Comment by mattrepl** [comment]
Closing this for now. A different graph representation might be preferred over complicating the functions supporting existing representations.

**Comment by aysylu** [comment]
I think your implementation is great and doesn't over complicate the functions at all. I'd welcome your contribution, if you reconsider. It'd be very helpful if you could either run criterium on your graph before and after changes. Or if you share your graph, I could do it. I can take care of adding the tests as well.

**Pull request closed without merging**
