### PR TITLE
Move to Clojure 1.7 and cljc

### LINKED ISSUE #60: Move to Clojure 1.7 and convert to cljc
This will pave the way for enabling Clojurescript (#45).

### PR DESCRIPTION
**Pull request by danielcompton**
This is a WIP. Interestingly, upgrading to 1.7 breaks quite a few tests, so this needs to be tracked down before I can migrate to clic.

Fixes #60 and paves the way for #45.

Blockers

- [x] clojure.data.priority-map needs to have a ClojureScript version available. https://github.com/tailrecursion/cljs-priority-map could be an alternative option.

Tasks:
- [ ] alg-generic
- [ ] attr
- [ ] gen
- [ ] graph
- [ ] io
- [ ] label
- [ ] multigraph
- [ ] Add testing framework to run ClojureScript tests at same time as Clojure tests

### CODE REVIEW

**Comment by danielcompton** [comment]
It looks like Clojure 1.6 has (test) breaking changes too. I'm going through the failed tests but mostly they look to be reordering of semantically unordered vectors.

**Comment by aysylu** [comment]
Clojure 1.7 was released on 6/30/2015: http://mvnrepository.com/artifact/org.clojure/clojure/1.7.0, so we can move forward with merging this PR.

@danielcompton, your last commit message says it's WIP. Is there anything else you'd like to add to the PR?

**Comment by danielcompton** [comment]
At some point it may be worth revisiting vector ordering being significant, but it's not specifically important for this. I'll take another look at this soon and refresh my memory about what's left.

**Comment by danielcompton** [comment]
The major effort is setting up a testing framework to run the tests in Clojure and ClojureScript, there's a bit of work porting some platform specific code, but it's not too bad.

**Comment by danielcompton** [comment]
@aysylu I don't have a lot of time to port this over to cljs at the moment. If you're amenable to the idea, you could merge this PR now, and let people make new PR's to port individual namespaces one at the time. At the moment I think I'm the bottleneck on this.

**Comment by aysylu** [comment]
@danielcompton: sounds good. I'll merge the PR and update #45 with the leftover tasks to port to cljfs. Thanks for your contribution!

**Pull request merged**
